name: 'Limelight - DB Processor'
author: 'Burnett01'
description: 'This action is used to process MySQL INSERT statements based on key-value maps into a database. Processing includes escaping the values (prepared-statements).'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'edit-3'  
  color: 'gray-dark'
